deck: Implement unique identification of cards by assigning an id to each card
shivansh-bhatnagar18/multiplayer-uno pull request #14
Opened 2024-05-28 11:45 UTC by sethdivyansh

…each card

first created an id as card-type-color-value
and to uniquely identify the same type color value card, I created an card_num array that will to uniquely identify these card finnaly created an unique id card-type-color-value-num_card[id]

Fixes #<issue>

<details>
<summary>Screenshots and screen captures</summary>
</details>

<details>
<summary>Self-review checklist</summary>

- [ ] Self reviewed the changes for clarity and maintainability (variable names, code reuse, readability, etc.).
- [ ] Highlights technical choices and bugs encountered.
- [ ] Calls out remaining decisions and concerns.
- [ ] Automated tests verify logic where appropriate.
- [ ] Each commit is a coherent idea.
- [ ] Commit message(s) explain reasoning and motivation for changes.

Completed manual review and testing of the following:

- [ ] Visual appearance of the changes.
- [ ] End-to-end functionality of buttons, interactions and flows.
- [ ] Corner cases, error conditions, and easily imagined bugs.
</details>

2024-05-28 18:11 UTC, sethdivyansh commented on backend/uno-game-engine/deck.js
> +    let card_num = [];
Yes, I realized my mistake later. I have corrected it; please review the updated version.

2024-05-30 09:34 UTC, kuv2707 commented
@sethdivyansh Please rebase your branch against `upstream/main` and resolve the merge conflicts. 
You'd also have to deal with types now that this module is converted to TS.

I'l merge it then.

2024-05-30 11:19 UTC, sethdivyansh commented
@kuv2707 I have resolved all the conflicts. Please review the PR and merge it.

2024-05-30 11:40 UTC, kuv2707 commented on backend/uno-game-engine/types.d.ts
> +    id: string;
The typo should be fixed in the original commit itself. Refer to the docs, where an example is illustrated for this.

2024-05-30 11:59 UTC, sethdivyansh commented on backend/uno-game-engine/types.d.ts
> +    id: string;
done 👍

2024-05-30 16:59 UTC, kuv2707 commented on backend/uno-game-engine/types.d.ts
> +    id: string;
Great!
Now the commit message doesn't render well.

A part of the heading extends to the content. Try to write a concise heading.

There are also dome typos.

2024-05-30 17:11 UTC, kuv2707 requested changes

2024-05-30 17:11 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +    let id = `card-${type}-${color}-${value}`;
Prefer const for variables which do not change. Eslint should have given an error.

2024-05-30 17:11 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +    let uid = `${id}-${sameCardCount[id]}`;
Same here

2024-05-30 18:07 UTC, sethdivyansh commented
@kuv2707 I have made all the changes.

2024-05-31 06:14 UTC, kuv2707 commented
@sethdivyansh  Please add the "Fixes" clause in the commit message.

2024-05-31 06:43 UTC, sethdivyansh commented
Done

2024-05-31 07:09 UTC, sethdivyansh commented
> Done

2024-05-31 12:14 UTC, kuv2707 commented
@sethdivyansh Please add the motivation to use a custom-generated ID instead of approaches like uuid etc in the PR description.
There had been some discussion regarding it in the issue page.

This PR is ready to be merged. Will do it once the event begins officially.

2024-05-31 12:51 UTC, sethdivyansh commented
@kuv2707 @shivansh-bhatnagar18 I have mentioned the reasons for choosing custom IDs. If you feel using UUIDs is a better approach, please let me know, and I will make the desired changes accordingly.

2024-05-31 12:54 UTC, kuv2707 commented
No, this approach is fine. I just wanted you to mention the reasoning in the PR description for future reference.

2024-05-31 16:13 UTC, kuv2707 commented
No, this approach is fine. I just wanted you to mention the reasoning in the PR description for future reference.

2024-05-31 19:54 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
>      //todo: Implement unique identification of cards by assigning an id to each card
@sethdivyansh  Remove this todo comment.

2024-06-01 06:43 UTC, sethdivyansh commented on backend/uno-game-engine/deck.ts
>      //todo: Implement unique identification of cards by assigning an id to each card
I have removed the comment.

2024-06-01 10:31 UTC, merged

2024-06-01 10:31 UTC, kuv2707 commented
Merged, thanks @sethdivyansh !