deck: completed function to create and shuffle a UNO card deck.
shivansh-bhatnagar18/multiplayer-uno pull request #30
Opened 2024-05-31 18:53 UTC by sethdivyansh

- added black as a color in CardColor in types.d.ts
    - separated the values of special cards and wild cards into two arrays named specialValues and wildCardValues, respectively.
    - Iterates over each color in the colors array.
      For each color:
      * Iterates over each number value (0 to 9) in the numValues array and adds two cards of that color for each number, except for '0' where only one card is added.
      * Iterates over each special value in the specialValues array and adds two cards of that color for each special value.
      * If the color is 'black', iterates over each wild card value in the wildCardValue array and adds four cards of that color for each wild card value.

## Description
[Provide a brief description of the changes made in this pull request.]

## Motivation and Context
[Explain the motivation behind these changes and provide any relevant context.]

## How to Test
[Describe the steps to test the changes made in this pull request.]

## Related Issues
[If applicable, mention any related issues or pull requests.]

## Checklist
- [ ] I have tested these changes locally.
- [ ] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
[If your changes include any visual updates, provide screenshots here.]

2024-06-02 06:06 UTC, kuv2707 commented
Can you edit the commit message to occupy less width per line?

2024-06-02 07:06 UTC, sethdivyansh commented
> Can you edit the commit message to occupy less width per line?

I have shortened the commit message.

2024-06-02 17:22 UTC, kuv2707 commented
Great work!
It would be further great if you could add some tests to verify if the array generated has all the cards in the right amount.
Feel free to take the test cases from [this PR](https://github.com/shivansh-bhatnagar18/multiplayer-uno/pull/54/files) if you don't feel like writing it yourself (do credit the author for it though).

2024-06-02 17:42 UTC, kuv2707 requested changes
Posted some minor comments.
Overall, this seems promising and can be merged once the comments are addressed and tests are added.

PS. the commit message is perfect. Kudos for that!

2024-06-02 17:42 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +const deck: Array<UNOCard> = [];
Seems like this variable is useless.
You can go ahead and remove it.

2024-06-02 17:42 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +const numValues: Array<CardNumbers> = [
Make CardNumbers singular.

2024-06-02 17:42 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +const specialValues: Array<SpecialCardNames> = ['skip', 'reverse', 'draw2'];
Here too, types should be singular, unless they are an array

2024-06-02 17:42 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +            });
The generation logic seems fine.
You can add tests to check if it generates the entire suite correctly.

2024-06-02 17:42 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +const wildCardValue: Array<SpecialCardNames> = ['colchange', 'draw4'];
The variable name should be plural.

2024-06-02 17:44 UTC, kuv2707 commented on backend/uno-game-engine/deck.ts
> +const deck: Array<UNOCard> = [];
This would also make the eslint-backend check pass.

2024-06-03 08:04 UTC, sethdivyansh commented
@kuv2707 Please check I have made the desired changes and added a test to validate the created function.

2024-06-03 08:20 UTC, kuv2707 approved these changes
Looks great!

2024-06-03 08:20 UTC, kuv2707 commented on backend/tests/deck.test.ts
> +describe('getShuffledCardDeck', () => {
Appreciate the thorough testing!

2024-06-03 08:22 UTC, merged