Server: Route Handler for /event
shivansh-bhatnagar18/multiplayer-uno pull request #57
Opened 2024-06-02 15:50 UTC by asmit27rai

### Controller For Post  /event EndPoint
Fixes #45

## Description
I worked on three file firstly i make getallclient function in eventRecipient secondly create post route in gameRoute file and finally create relayGameEvent in gameController file where i take req and put send it to all connected client...

## Motivation and Context
To Relay The Event To The Connected User Only

## Related Issues
Make Function That Update GameState.

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

2024-06-02 17:48 UTC, kuv2707 commented on backend/controllers/gameControllers.js
> +        client.json(gameEvent);
This is indeed the flow I had in mind, but we'd need to store a couple more things alongside the response object in the map in eventRecipient. I'll update the type soon, and you can accomodate it here.

2024-06-02 17:49 UTC, kuv2707 commented on backend/eventRecipients.ts
> +    return Array.from(clients.values());
Why not just return `clients.values()`?

2024-06-02 17:55 UTC, asmit27rai commented on backend/eventRecipients.ts
> +    return Array.from(clients.values());
> Why not just return `clients.values()`?

Because in we won't able to use forEach in place were we import it. That, Why I did It.

2024-06-02 17:57 UTC, asmit27rai commented on backend/controllers/gameControllers.js
> +        client.json(gameEvent);
> This is indeed the flow I had in mind, but we'd need to store a couple more things alongside the response object in the map in eventRecipient. I'll update the type soon, and you can accomodate it here.

I think we can use create gameStats function also to modify the game stats as per new events..

2024-06-03 07:14 UTC, kuv2707 commented on backend/eventRecipients.ts
> +    return Array.from(clients.values());
Alright

2024-06-03 19:07 UTC, kuv2707 commented
I have added some structure for sending events. Please update the PR, using those functions

2024-06-04 11:54 UTC, asmit27rai reviewed
Change Some Of The Changes made in master repo.

2024-06-04 11:55 UTC, asmit27rai commented
> I have added some structure for sending events. Please update the PR, using those functions

Done

2024-06-06 09:27 UTC, kuv2707 commented
@asmit27rai Please resolve the conflicts to progress the PR

2024-06-06 11:05 UTC, asmit27rai commented
> @asmit27rai Please resolve the conflicts to progress the PR

Done

2024-06-06 16:26 UTC, kuv2707 requested changes
The button thing should be done in its own PR.

Suggested some changes in the implementation

2024-06-06 16:26 UTC, kuv2707 commented on frontend/src/library/button.tsx
>  function Button({ onClick, children }: ButtonProps) {
This isn't supposed to be in this PR.

2024-06-06 16:26 UTC, kuv2707 commented on backend/src/controllers/gameControllers.js
> +    connectedClients.forEach((client) => {
Please make use of the `scheduleSend` function in `eventRecipient.ts`.

2024-06-06 17:07 UTC, asmit27rai commented on backend/src/controllers/gameControllers.js
> +    connectedClients.forEach((client) => {
Should I use scheduleSend function instead of getAllClients function?

2024-06-07 12:40 UTC, kuv2707 commented on backend/src/controllers/gameControllers.js
> +    connectedClients.forEach((client) => {
@asmit27rai  You should modify the `getAllClients` to return an array of ids.
Eventually, we'd filter out the client ids to which we want to propagate the events. For now, we propagate all events to all clients. 
For propagation, you use the `scheduleSend` function.

2024-06-07 12:44 UTC, kuv2707 commented on backend/src/controllers/gameControllers.js
> +    connectedClients.forEach((client) => {
Also, the function should be renamed to `handleEvent` since it will handle updating the game state, propagating chat messages (to be implemented) and other such features
(basically all `AppEvents`).

2024-06-07 14:48 UTC, asmit27rai commented on backend/src/controllers/gameControllers.js
> +    connectedClients.forEach((client) => {
> @asmit27rai You should modify the `getAllClients` to return an array of ids. Eventually, we'd filter out the client ids to which we want to propagate the events. For now, we propagate all events to all clients. For propagation, you use the `scheduleSend` function.

I rewrite the code accordingly.
Please check for it.

2024-06-07 15:13 UTC, kuv2707 reviewed
Posted a suggestion.
Also change the commit message to around 72 characters per line, and use passive voice (don't write I did / I added )

For this, you can discard your changes in `scheduleSend` part and then run `git commit --amend` and insert line breaks where required.
then run `git push --force`.
This changes both the file and the commit message.

The PR should be fit to merge then.

2024-06-07 15:19 UTC, asmit27rai commented on backend/src/eventRecipients.ts
> +    if (eventQueue.has(clientId)) {
Can You Please elaborate what i have to remove from here?

2024-06-07 15:20 UTC, kuv2707 commented on backend/src/eventRecipients.ts
> +    if (eventQueue.has(clientId)) {
The whole `scheduleSend` function should be left unchanged.

2024-06-07 15:38 UTC, asmit27rai commented on backend/src/eventRecipients.ts
> +    if (eventQueue.has(clientId)) {
@kuv2707 Done.

2024-06-07 17:17 UTC, kuv2707 commented
The commit message still isnt perfect(lines are too wide), but can be ignored.

2024-06-07 17:17 UTC, merged

2024-06-07 17:17 UTC, kuv2707 commented
Merged, thanks @asmit27rai